version: 2.1

executors:
  node14-executor:
    docker:
      - image: circleci/node:14.16.1

jobs:
  release:
    executor: node14-executor
    steps:
      - checkout
      - run: npm install
      - run: GH_TOKEN=$GH_TOKEN npx semantic-release

workflows:
  version: 2
  build:
    jobs:
      - release:
          context: docker
          filters:
            branches:
              only:
                - master